name: aml_proj_ci
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - networkx
  - matplotlib
  - pytorch::pytorch
  - pytorch::cpuonly    # prevents CUDA wheels from being downloaded in CI
  - pytest
  - pytest-timeout
